public class MovieHouseDesign extends javax.swing.JPanel {

    /**
     * Creates new form MovieHouseDesign
     */
    public MovieHouseDesign() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        photolb = new javax.swing.JLabel();
        namelb = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 0, 0));
        setLayout(null);

        photolb.setForeground(new java.awt.Color(255, 255, 255));
        photolb.setText("//photo");
        add(photolb);
        photolb.setBounds(30, 30, 280, 160);

        namelb.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        namelb.setForeground(new java.awt.Color(255, 255, 255));
        namelb.setText("//name");
        add(namelb);
        namelb.setBounds(80, 210, 140, 50);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JLabel namelb;
    public javax.swing.JLabel photolb;
    // End of variables declaration//GEN-END:variables
}
